### ISSUE TITLE
1주차 문제 - 예진

### ISSUE THREAD

**Issue by c0olcode** [Kernel360-cell1/architecture-study#6]
NoSQL이 필요한 사례에 대해 서술하시오.
- 아주 낮은 응답 지연시간(latency)이 요구된다.
- 다루는 데이터가 비정형이기 때문에 관계형 데이터가 아니다.
- 데이터(JSON, YAML, XMl 등)를 직렬화하거나 역직렬화 할 수 있기만 하면 된다.
- 아주 많은 양의 데이터를 저장할 필요가 있다.

대규모 데이터베이스를 샤드라는 작은 단위로 분할하는 기술은?
: 샤딩

메시지의 무손실을 보장하는 비동기 통신을 지원하는 컴포넌트는?
: 메세지 큐

데이터가 잠시 보관되는 곳으로, 데이터베이스보다 접근이 빨라 성능을 개선시킬 수 있고 데이터베이스의 부하를 줄일 수 있는 것은?
: 캐시 계층

**Comment by yejincode** [comment]
NoSQL이 필요한 사례에 대해 서술하시오.
- 아주 낮은 응답 지연시간(latency)이 요구된다.
- 다루는 데이터가 비정형이기 때문에 관계형 데이터가 아니다.
- 데이터(JSON, YAML, XMl 등)를 직렬화하거나 역직렬화 할 수 있기만 하면 된다.
- 아주 많은 양의 데이터를 저장할 필요가 있다.

대규모 데이터베이스를 샤드라는 작은 단위로 분할하는 기술은?
: 샤딩

메시지의 무손실을 보장하는 비동기 통신을 지원하는 컴포넌트는?
: 메세지 큐

데이터가 잠시 보관되는 곳으로, 데이터베이스보다 접근이 빨라 성능을 개선시킬 수 있고 데이터베이스의 부하를 줄일 수 있는 것은?
: 캐시 계층
